# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: django-backend
# spec:
#   replicas: {{ .Values.replicaCount }}
#   selector:
#     matchLabels:
#       app: django-backend
#   template:
#     metadata:
#       labels:
#         app: django-backend
#     spec:
#       containers:
#         - name: django-backend
#           image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
#           ports:
#             - containerPort: 8000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: django-backend-service
# spec:
#   selector:
#     app: django-backend
#   type: {{ .Values.service.type }}
#   ports:
#     - port: 8000
#       targetPort: 8000
#       nodePort: {{ .Values.service.backendPort }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend-service
spec:
  type: {{ .Values.service.backend.type }} # Use the backend service type from values.yaml
  selector:
    app: django-backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.backend.nodePort | default "30006" }} # Use the backend nodePort from values.yaml, with a default value of 30006
