apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-cronjob
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django
            image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
            command: {{ toJson .Values.cronJob.command }}
            env:
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.cronJob.djangoSettingsModule }}
            - name: DATABASE_URL
              value: {{ .Values.cronJob.databaseUrl }}
          restartPolicy: OnFailure
