apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-cronjob
spec:
  schedule: "0 7 * * *"  # This runs the job daily at 7 AM

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django
            image: mallaashutosh/backend:latest  # Replace with your Django image
            command: ["python", "manage.py", "fetchdata"]  # Replace with your management command
            env:
            - name: DJANGO_SETTINGS_MODULE
              value: stocks_monitoring.settings
            - name: DATABASE_URL
              value: mysql://root:ashu1234@mysql-service:3306/techdemo
          restartPolicy: OnFailure